repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        entry: flake8
        types: [file, python]

  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        types: [file, python]

  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        types: [file, python]

default_language_version:
  python: python3.8
