"""Remove root flag, add story-root table

Revision ID: 5bf94ae81c59
Revises: ab38f180a950
Create Date: 2022-02-14 16:28:40.775145

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5bf94ae81c59"
down_revision = "ab38f180a950"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "story_root",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("story", sa.String(length=36), nullable=True),
        sa.Column("node", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["node"], ["node.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["story"], ["story.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("node", "is_root")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "node",
        sa.Column(
            "is_root",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("story_root")
    # ### end Alembic commands ###
