"""initial

Revision ID: a5bbd3de82f5
Revises:
Create Date: 2021-11-24 10:17:04.178298

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5bbd3de82f5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "story",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "node",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("story", sa.Integer(), nullable=True),
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("text", sa.VARCHAR(length=200), nullable=False),
        sa.ForeignKeyConstraint(["story"], ["story.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_node_name"), "node", ["name"], unique=False)
    op.create_table(
        "option",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("next", sa.Integer(), nullable=True),
        sa.Column("cur_node", sa.Integer(), nullable=True),
        sa.Column("text", sa.VARCHAR(length=200), nullable=False),
        sa.ForeignKeyConstraint(["cur_node"], ["node.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["next"], ["node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_option_cur_node"), "option", ["cur_node"], unique=False)
    op.create_index(op.f("ix_option_next"), "option", ["next"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_option_next"), table_name="option")
    op.drop_index(op.f("ix_option_cur_node"), table_name="option")
    op.drop_table("option")
    op.drop_index(op.f("ix_node_name"), table_name="node")
    op.drop_table("node")
    op.drop_table("story")
    # ### end Alembic commands ###
