"""Update story id and add is_root field for node

Revision ID: ab38f180a950
Revises: a5bbd3de82f5
Create Date: 2022-01-18 11:49:15.220939

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from alembic.op import create_foreign_key, drop_constraint

revision = "ab38f180a950"
down_revision = "a5bbd3de82f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "node",
        sa.Column(
            "is_root", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    drop_constraint("node_story_fkey", "node")
    op.alter_column(
        "node",
        "story",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=36),
        existing_nullable=True,
    )
    op.alter_column(
        "story",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=36),
        existing_nullable=False,
        existing_server_default=sa.text("nextval('story_id_seq'::regclass)"),
    )

    create_foreign_key(
        constraint_name="node_story_fkey",
        source_table="node",
        referent_table="story",
        local_cols=["story"],
        remote_cols=["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    drop_constraint("node_story_fkey", "node")
    op.alter_column(
        "story",
        "id",
        existing_type=sa.String(length=36),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("nextval('story_id_seq'::regclass)"),
    )
    op.alter_column(
        "node",
        "story",
        existing_type=sa.String(length=36),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.drop_column("node", "is_root")

    create_foreign_key(
        constraint_name="node_story_fkey",
        source_table="node",
        referent_table="story",
        local_cols=["story"],
        remote_cols=["id"],
    )
    # ### end Alembic commands ###
