"""Initial

Revision ID: ba5c7849389e
Revises:
Create Date: 2021-11-19 17:31:04.191470

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ba5c7849389e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "node",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("story", sa.Integer(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("text", sa.VARCHAR(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["story"], ["story.id"], ondelete="CASCADE", use_alter=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_node_story"), "node", ["story"], unique=False)
    op.create_table(
        "story",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("root", sa.Integer(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["root"], ["node.id"], ondelete="CASCADE", use_alter=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_story_root"), "story", ["root"], unique=False)
    op.create_table(
        "option",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("next", sa.Integer(), nullable=False),
        sa.Column("text", sa.VARCHAR(length=200), nullable=False),
        sa.ForeignKeyConstraint(["next"], ["node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_option_next"), "option", ["next"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_option_next"), table_name="option")
    op.drop_table("option")
    op.drop_index(op.f("ix_story_root"), table_name="story")
    op.drop_table("story")
    op.drop_index(op.f("ix_node_story"), table_name="node")
    op.drop_table("node")
    # ### end Alembic commands ###
